name: Publish npm package

on:
  push: 
    branches:
    - master
    paths:
    - 'npm-bacon/*'
    - '.github/workflows/npm.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Add GPR token to .npmrc
      run: echo //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN >> npm-bacon/.npmrc
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Publish the package
      run: |
           cd npm-bacon/
           npm publish
